
/**
 *
 * @author Muhammad Maulana (2310010375)
 */

// Import ini untuk fitur "Simpan File"
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

// Import ini untuk "Pop-up" dan "Pilih File"
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

// Import ini untuk listener real-time (JTextArea)
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class PenghitungKataUI extends javax.swing.JFrame {

    /**
     * Creates new form PenghitungKataUI
     */
    public PenghitungKataUI() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        // Ini untuk listener real-time pada jTextAreaInput 
    jTextAreaInput.getDocument().addDocumentListener(new DocumentListener() {
        public void insertUpdate(DocumentEvent e) {
            hitungSemua(); // Panggil saat mengetik
        }
        public void removeUpdate(DocumentEvent e) {
            hitungSemua(); // Panggil saat menghapus
        }
        public void changedUpdate(DocumentEvent e) {
            // Abaikan
        }
    });
    }
    private void hitungKataSaja() {
        String teks = jTextAreaInput.getText(); // Ganti jika nama JTextArea Anda beda
        
        int jumlahKata = 0;
        if (!teks.trim().isEmpty()) {
            // Ini adalah Ekspresi Reguler (Regex)
            String[] kata = teks.trim().split("\\s+"); // Pecah berdasarkan spasi
            jumlahKata = kata.length;
        }
        
        // Update HANYA lblKata
        lblKata.setText(String.valueOf(jumlahKata));
    }
    
    private void hitungSemua() {
        // 1. Ambil teks dari JTextArea
        String teks = jTextAreaInput.getText(); // Ganti jika nama JTextArea Anda beda

        // 2. Hitung Karakter
        int jumlahKarakter = teks.length();

        // 3. (Bagian Hitung Kata DIHAPUS dari sini)

        // 4. Hitung Kalimat (Variasi)
        int jumlahKalimat = 0;
        if (!teks.trim().isEmpty()) {
            String[] kalimat = teks.trim().split("[.!?]+"); 
            jumlahKalimat = kalimat.length;
        }

        // 5. Hitung Paragraf (Variasi)
        int jumlahParagraf = 0;
        if (!teks.trim().isEmpty()) {
            String[] paragraf = teks.trim().split("(\\n[\\s]*\\n)+|(\\r\\n[\\s]*\\r\\n)+");
            jumlahParagraf = paragraf.length;
        }

        // 6. Update tampilan JLabel (TANPA lblKata)
        lblKarakter.setText(String.valueOf(jumlahKarakter));
        lblKalimat.setText(String.valueOf(jumlahKalimat));
        lblParagraf.setText(String.valueOf(jumlahParagraf));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Judul = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaInput = new javax.swing.JTextArea();
        jButtonHitung = new javax.swing.JButton();
        jButtonCari = new javax.swing.JButton();
        jButtonSimpan = new javax.swing.JButton();
        jTextFieldCari = new javax.swing.JTextField();
        lblKarakter = new javax.swing.JLabel();
        lblKata = new javax.swing.JLabel();
        lblKalimat = new javax.swing.JLabel();
        lblParagraf = new javax.swing.JLabel();
        jLabelKarakterInfo = new javax.swing.JLabel();
        jLabelKataInfo = new javax.swing.JLabel();
        jLabelKalimatInfo = new javax.swing.JLabel();
        jLabelParagrafInfo = new javax.swing.JLabel();
        jLabelCariInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        Judul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Judul.setText("Aplikasi Penghitung Kata");
        jPanel1.add(Judul);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(198, 255, 255));

        jTextAreaInput.setColumns(20);
        jTextAreaInput.setRows(5);
        jTextAreaInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextAreaInputKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTextAreaInput);

        jButtonHitung.setText("Hitung");
        jButtonHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHitungActionPerformed(evt);
            }
        });

        jButtonCari.setText("Cari");
        jButtonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCariActionPerformed(evt);
            }
        });

        jButtonSimpan.setText("Simpan");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });

        jTextFieldCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCariActionPerformed(evt);
            }
        });

        lblKarakter.setText("0");

        lblKata.setText("0");

        lblKalimat.setText("0");

        lblParagraf.setText("0");

        jLabelKarakterInfo.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabelKarakterInfo.setText("Karakter :");

        jLabelKataInfo.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabelKataInfo.setText("Total Kata :");

        jLabelKalimatInfo.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabelKalimatInfo.setText("Kalimat :");

        jLabelParagrafInfo.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabelParagrafInfo.setText("Paragraf :");

        jLabelCariInfo.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabelCariInfo.setText("Cari Kata :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCariInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelKarakterInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelParagrafInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelKalimatInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblKarakter, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblParagraf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblKalimat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblKata, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCari, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelKataInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCariInfo)
                    .addComponent(jTextFieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCari)
                    .addComponent(jButtonSimpan))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKarakterInfo)
                    .addComponent(lblKarakter))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKalimat)
                    .addComponent(jLabelKalimatInfo))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblParagraf)
                    .addComponent(jLabelParagrafInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKataInfo)
                    .addComponent(lblKata)
                    .addComponent(jButtonHitung))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCariActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Simpan Teks dan Hasil");

        int pilihan = fileChooser.showSaveDialog(this);

        if (pilihan == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();

            if (!file.getAbsolutePath().endsWith(".txt")) {
                file = new File(file.getAbsolutePath() + ".txt");
            }

            try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {

                writer.write("--- TEKS PENGGUNA ---\n");
                writer.write(jTextAreaInput.getText());
                writer.newLine();
                writer.newLine();

                writer.write("--- HASIL PERHITUNGAN ---\n");

                writer.write("Jumlah Karakter: " + lblKarakter.getText() + "\n");
                writer.write("Jumlah Kata: " + lblKata.getText() + "\n");
                writer.write("Jumlah Kalimat: " + lblKalimat.getText() + "\n");
                writer.write("Jumlah Paragraf: " + lblParagraf.getText() + "\n");

                JOptionPane.showMessageDialog(this, "Hasil berhasil disimpan ke:\n" + file.getAbsolutePath());

            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error: Gagal menyimpan file.\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jButtonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCariActionPerformed
        // TODO add your handling code here:
        String kataCari = jTextFieldCari.getText();

        String teks = jTextAreaInput.getText();
        int jumlahDitemukan = 0;
        if (!kataCari.isEmpty() && !teks.isEmpty()) {
            String[] kata = teks.split("[\\s.,!?]+");

            for (String k : kata) {
                if (k.equalsIgnoreCase(kataCari)) {
                    jumlahDitemukan++;
                }
            }
        }
        JOptionPane.showMessageDialog(this, "Kata '" + kataCari + "' ditemukan sebanyak " + jumlahDitemukan + " kali.");
    }//GEN-LAST:event_jButtonCariActionPerformed

    private void jButtonHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHitungActionPerformed
        // TODO add your handling code here:
        hitungKataSaja();
    }//GEN-LAST:event_jButtonHitungActionPerformed

    private void jTextAreaInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaInputKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAreaInputKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenghitungKataUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenghitungKataUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenghitungKataUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenghitungKataUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenghitungKataUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Judul;
    private javax.swing.JButton jButtonCari;
    private javax.swing.JButton jButtonHitung;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JLabel jLabelCariInfo;
    private javax.swing.JLabel jLabelKalimatInfo;
    private javax.swing.JLabel jLabelKarakterInfo;
    private javax.swing.JLabel jLabelKataInfo;
    private javax.swing.JLabel jLabelParagrafInfo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaInput;
    private javax.swing.JTextField jTextFieldCari;
    private javax.swing.JLabel lblKalimat;
    private javax.swing.JLabel lblKarakter;
    private javax.swing.JLabel lblKata;
    private javax.swing.JLabel lblParagraf;
    // End of variables declaration//GEN-END:variables
}
